### ISSUE TITLE
No such file or directory: './_noise/0000.pt'`

### ISSUE THREAD

**Issue by fikry102** [yunqing-me/RICK#4]
`noise_fisher    = torch.load(f'./_noise/{str(j).zfill(4)}.pt').cuda()`
line 227 in train_dynamic_update_prune.py

`FileNotFoundError: [Errno 2] No such file or directory: './_noise/0000.pt'`

I found a file named noise.pt in the repo.
Should I change "./_noise/{str(j).zfill(4)}.pt" into "noise.pt"?

**Comment by yunqing-me** [comment]
Thank you for your interest in our work. I took a look at the uploaded code. 

In general, the dimension of the noise to estimate the fisher information should have the same dimension of the input to the image generator (this means you can also generate them by yourself). 

I have uploaded some generated random noise as examples in the repo. Please feel free to check out!
