### ISSUE TITLE
Higher FID in Comparision to Paper

### ISSUE THREAD

**Issue by prajwalsingh** [yunqing-me/RICK#5]
Dear Authors, thank you for your work and for publicizing the code. We tried replicating the results of AFHQ_Cat, but we got the FID score around 62.03. Also, we observed that running eval on every 50th epoch makes the training very slow. We would like to know if is it because of eval frequency, if we reduce it, we can get paper-reported FID, or if something else is the reason.

**Comment by yunqing-me** [comment]
Hi: thanks for the interest. Yes you could lower the eval gap and train a bit longer (say >2k iterations) to see the results. Meanwhile, you can also share the train/eval setup in your trials if necessary.
